export const GET_CATEGORY_LIST_REQUEST = 'Category/GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_SUCCESS = 'Category/GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILED = 'Category/GET_CATEGORY_LIST_FAILED';
