// GET Category List
export const GET_CATEGORY_LIST_REQUEST = 'Category/GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_SUCCESS = 'Category/GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_FAILED = 'Category/GET_CATEGORY_LIST_FAILED';

// GET Category Detail
export const GET_CATEGORY_DETAIL_REQUEST = 'Category/GET_CATEGORY_DETAIL_REQUEST';
export const GET_CATEGORY_DETAIL_SUCCESS = 'Category/GET_CATEGORY_DETAIL_SUCCESS';
export const GET_CATEGORY_DETAIL_FAILED = 'Category/GET_CATEGORY_DETAIL_FAILED';

// POST Create Category
export const POST_CREATE_CATEGORY_REQUEST = 'Category/POST_CREATE_CATEGORY_REQUEST';
export const POST_CREATE_CATEGORY_FAILED = 'Category/POST_CREATE_CATEGORY_FAILED';

// PATCH Update Category
export const PATCH_UPDATE_CATEGORY_REQUEST = 'Category/PATCH_UPDATE_CATEGORY_REQUEST';
export const PATCH_UPDATE_CATEGORY_FAILED = 'Category/PATCH_UPDATE_CATEGORY_FAILED';

// DELETE Category
export const DELETE_CATEGORY_REQUEST = 'Category/DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_FAILED = 'Category/DELETE_CATEGORY_FAILED';
