export const SET_ALL_PRODUCT = 'SET_ALL_PRODUCT';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
